### ISSUE TITLE
"Bad file descriptor" error

### ISSUE THREAD

**Issue by MaxBear** [afitzek/hasura-metric-adapter#30]
I am pulling docker image ghcr.io/afitzek/hasura-metric-adapter:v0.1.6 and configured following in my docker-compose file so that hasura-metric-adapter will read log files from shared name volume from hasura graphql engine
```
    volumes:
      - logs:/tmp/log
    environment:
      LOG_FILE: /tmp/log/stdout.log
```
I am getting exception  
```
dev-hasura-metric-adapter-1  | hasura-metrics-adapter on 0.0.0.0:9090 for hasura at http://graphql-engine:8080 parsing hasura log '/tmp/log/stdout.log'
dev-hasura-metric-adapter-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" })', src/logreader.rs:44:69
dev-hasura-metric-adapter-1  | stack backtrace:
dev-hasura-metric-adapter-1  |    0:       0x40005dd9ec - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
dev-hasura-metric-adapter-1  |                                at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
dev-hasura-metric-adapter-1  |    1:       0x40005dd9ec - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
dev-hasura-metric-adapter-1  |                                at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
dev-hasura-metric-adapter-1  |    2:       0x40005dd9ec - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
dev-hasura-metric-adapter-1  |                                at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
dev-hasura-metric-adapter-1  |    3:       0x40005dd9ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
dev-hasura-metric-adapter-1  |                                at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
```
it looks there are errors on accessing and parsing hasura logs. Please provide some help on this, thanks.

**Comment by MaxBear** [comment]
```mkfifo /tmp/log/stdout.log``` solves the issue
